grid:
  title: 3rdTest-EulerA
  description: 3rdTest-EulerA
  format: jpg
  author: Unspecified
axes:
  Denoising: 0.4, 0.5, 0.6 # (0.4, 0.5)
  Steps: 10, 12, 15, 18, 20, 22, 25 # (10 -> 20)
  HighRes Steps: 4, 7, 10, 15, 20 # (10)
  CFG Scale: 7, 9
